# Generated by Django 5.0.6 on 2024-07-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_dataset_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
