# Generated by Django 5.0.6 on 2024-07-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_profile_service_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
