# Generated by Django 5.0.6 on 2024-08-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_profile_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
