# Generated by Django 5.0.6 on 2024-07-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cleaning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.DeleteModel(
            name='DataCleaningTask',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
